PI-9763 fix product export for website specific items
shopgate/cart-integration-magento2-base pull request #43
Opened 2019-09-12 16:20 UTC by Skistims

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I updated the CHANGELOG.md

2019-09-12 17:24 UTC, augsteyer requested changes

2019-09-12 17:24 UTC, augsteyer commented on src/Helper/Product/Type/Grouped.php
> +        return $productCollection;
you return something else now, no docBlock update is seen though. Please adjust return and check where this is used to make sure that it expects this to be a collection of items instead of an array of items

2019-09-12 17:24 UTC, augsteyer commented on src/Helper/Product/Type/Configurable.php
> +        $productCollection->addStoreFilter();
double check that this does not need a storeId specified

2019-09-13 12:18 UTC, Skistims commented on src/Helper/Product/Type/Configurable.php
> +        $productCollection->addStoreFilter();
yup. it has a fallback to it's own storeHandler and I tested it succesfully

2019-09-13 12:35 UTC, augsteyer approved these changes

2019-09-13 13:57 UTC, merged